#!/bin/bash
#
# 2020-02-15 J.Nider

realpath=$(readlink -f $0) # in case 'bake' was executed from a symbolic link
path=${realpath%/*} # full path of 'bake' script (minus the script name)

# include the linker rules automatically for convenience
source $path/ld_rules

#---------------------------
# compile .c file to .o file
#
# Depends on: CC compiler name
# Optional: CFLAGS additional flags to pass to compiler
#				SRC_PATH full path to source file
#				DST_PATH full path to destination file
#
function rule_compile_c()
{
   local target=$1
   local root=${target%.o}
   local suffix=${target##$root}
   [[ "$suffix" == ".o" ]] && [[ -f "$root.c" ]] || return -1

	# make sure the compiler is set
	[ $CC ] || {
		echo "${FUNCNAME[0]}: 'CC' variable must be set to the name of the compiler"
		exit
	}

   echo "Compiling $root.c to $root.o"

	local srcfile
	[ $SRC_PATH ] && srcfile=$SRC_PATH/
	srcfile+=$root.c

	local dstfile
	[ $DST_PATH ] && dstfile=$DSTPATH/
	dstfile+=$root.o

	local cmd="$CC $CFLAGS -c $srcfile -o $dstfile" 
   [ $__verbose ] && echo $cmd
   $cmd
}
