#!/bin/bash
#
# 2021-12-16 J.Nider

realpath=$(readlink -f $0) # in case 'bake' was executed from a symbolic link
path=${realpath%/*} # full path of 'bake' script (minus the script name)
source $path/ld_rules

#---------------------------
# compile .cu file to .o file
#
# Depends on: NVCC compiler name
# Optional: NVCCFLAGS additional flags to pass to compiler
#				SRC_PATH full path to source file
#				DST_PATH full path to destination file
#

function rule_cuda
{
   local target=$1
   local root=${target%.o}
   local suffix=${target##$root}

	local srcfile
	[ $SRC_PATH ] && srcfile=$SRC_PATH/
	srcfile+=$root.cu

	local dstfile
	[ $DST_PATH ] && dstfile=$DST_PATH/
	dstfile+=$root.o

   [[ "$suffix" == ".o" ]] && [[ -f "${SRC_PATH}/$root.cu" ]] || return -1

	# make sure the compiler is set
	[ $NVCC ] || {
		echo "${FUNCNAME[0]}: 'NVCC' variable must be set to the name of the compiler"
		exit
	}

   echo "Compiling $root.cu to $root.o"

	local cmd="$NVCC $NVCCFLAGS $srcfile -o $dstfile" 
   [ $__verbose ] && echo $cmd
   $cmd
}

