#!/bin/bash
#
# 2021-12-16 J.Nider

realpath=$(readlink -f $0) # in case 'bake' was executed from a symbolic link
path=${realpath%/*} # full path of 'bake' script (minus the script name)

# include the linker rules automatically for convenience
source $path/ld_rules

#---------------------------
# compile .cu file to .o file
#
# Depends on: NVCC compiler name
# Optional: NVCCFLAGS additional flags to pass to compiler
#				SRC_PATH full path to source file
#				DST_PATH full path to destination file
#

function rule_cuda
{
	local target=$1
	local flags=${2:-$NVCCFLAGS}
	local root=${target%.*}
	local deps
	local target_suffix=${target##*.}

	# make sure target is of the right type
	[[ "$target_suffix" =~ [oO] ]] || return -1

	# the first dependency is the source file, otherwise guess at the name
	_deps_of $target deps
	local srcfile=${deps[0]:-$root.cu}
	local suffix=${srcfile##*.}

	# make sure source file exists and is of the right type
	[[ "$suffix" == "cu" ]] && [[ -f "$srcfile" ]] || return -1

	# make sure the compiler is set
	[ $NVCC ] || {
		echo "${FUNCNAME[0]}: 'NVCC' variable must be set to the name of the compiler"
		exit
	}

	echo "Compiling $srcfile to $target"

	local cmd="$NVCC $flags -c $srcfile -o $target"
	[[ $__verbose ]] && echo $cmd
	$cmd
}

