#!/bin/bash
#
# 2021-11-14 J.Nider

#---------------------------
# link .o files to .elf file
#
# Depends on: LD linker name
#
function rule_link()
{
   local target=$1
	local flags=$2

   local root=${target%.*}
   local suffix=${target##$root}
   [[ "$suffix" == ".elf" ]] || return -1

	# make sure the linker is set
	[ $LD ] || {
		echo "${FUNCNAME[0]}: 'LD' variable must be set to the name of the linker"
		exit
	}

   echo "Linking $target"
	local deps
	_deps_of $target deps
	local cmd="$LD $LDFLAGS ${deps[@]} $LDLIBS -o $target" 
   [ $__verbose ] && echo $cmd
   $cmd
}
